spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

logging.level.root=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.web.authentication.AuthenticationWebFilter=DEBUG
#logging.level.org.springframework.security.core.userdetails.UserDetailsService=DEBUG



#Auth Properties
spring.security.oauth2.client.registration.okta.client-id=0oaiy0tyr1Q5OdnmL5d7
spring.security.oauth2.client.registration.okta.client-secret=5x5f3nHEXPeQLOGyUnARr2m6gr5SoouUGHlrsGYacVIYh_04qGLCdgMEZWjwHdho
spring.security.oauth2.client.registration.okta.redirect-uri=http://localhost:8080/login/oauth2/code/okta
spring.security.oauth2.client.provider.okta.authorization-uri=https://dev-07001217.okta.com/oauth2/v1/authorize
spring.security.oauth2.client.provider.okta.token-uri=https://dev-07001217.okta.com/oauth2/v1/token
spring.security.oauth2.client.provider.okta.user-info-uri=https://dev-07001217.okta.com/oauth2/v1/userinfo
spring.security.oauth2.client.provider.okta.jwk-set-uri=https://dev-07001217.okta.com/oauth2/v1/keys
spring.security.oauth2.client.registration.okta.scope=openid,profile,email

