spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

logging.level.root=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.web.authentication.AuthenticationWebFilter=DEBUG
#logging.level.org.springframework.security.core.userdetails.UserDetailsService=DEBUG

app.jwt.secret=Oh! My GraphQL Secret Key, You should be at least - 168 bites long inorder for to secure JWT HMAC-SHA algorithm. You make sure you are long enough not be vulnerable.