spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

logging.level.root=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.web.authentication.AuthenticationWebFilter=DEBUG
#logging.level.org.springframework.security.core.userdetails.UserDetailsService=DEBUG
