type Query {
    accounts: [BankAccount]
}

type Mutation {
    addAccount(account: BankAccountInput): BankAccount
}

type BankAccount {
    id: ID!
    client: Client!
    currency: Currency!
    balance: Float!
    status: String!
}

type Client {
    id: ID!
    firstName: String!
    middleName: String
    lastName: String
}

input BankAccountInput {
    id: ID!
    client: ClientInput!
    currency: Currency!
    balance: Float!
    status: String!
}

input ClientInput {
    id: ID!
    firstName: String!
    middleName: String
    lastName: String
}

# Supported currencies
enum Currency {
    EUR, CAD, USD
}